3.0.1/sources/libraries/csharp/index.md, 3.0.1/sources/plugin/magento/index.md, 3.0.1/sources/plugin/opencart/index.md, 3.0.1/sources/plugin/wordpress/index.md
Added Gluu server configuration changes required for WP plugin
=> Update WP plugin document

3.0.1/sources/libraries/csharp/index.md, 3.0.1/sources/libraries/node/index.md, 3.0.1/sources/libraries/perl/index.md, 3.0.1/sources/libraries/php/index.md, 3.0.1/sources/libraries/python/index.md
Fixed Protocol url for Perl, Python, Node, php, and C#
=> Fixed Protocol url

3.1.1/sources/install/index.md
=> openjdk-8 ppa

docs/sources/api/index.md
#334 - Add `params` map to `/get-authorization-url` api 
https://github.com/GluuFederation/oxd/issues/334
=> #334 - Add `params` map to `/get-authorization-url` api 

docs/sources/api/index.md, docs/sources/tutorial/index.md
#340 - Update oxd - 4.0 documentation with latest changes done
https://github.com/GluuFederation/oxd/issues/340
=> #340 - Update oxd - 4.0 documentation with latest changes done

docs/sources/release-notes/index.md
Updated Release Notes for oxd 4.0.b1
=> Updated Release Notes for oxd 4.0.b1

docs/sources/install/index.md
Update service operation and Uninstall steps for oxd 4.0 beta release
=> Update service operation and Uninstall steps for oxd 4.0 beta release

docs/sources/install/index.md
Updated installation steps for oxd 4.0.b1
=> Updated installation steps for oxd 4.0.b1

docs/sources/configuration/index.md
#210 - Introduce ability to lock oxd to list of specific IDPs
https://github.com/GluuFederation/oxd/issues/210
=> #210 - Introduce ability to lock oxd to list of specific IDPs

docs/sources/configuration/index.md
#50 - Provide fallback for all parameters
https://github.com/GluuFederation/oxd/issues/50
=> #50 - Provide fallback for all parameters

docs/mkdocs.yml, docs/sources/index.md, docs/sources/install/index.md
#383 - Updating docs from oxd 4.0 Beta to oxd 4.0 version
https://github.com/GluuFederation/oxd/issues/383
=> #383 - Updating docs from oxd 4.0 Beta to oxd 4.0 version

docs/mkdocs.yml, docs/sources/tracing/index.md
#182 - Add tracing metrics to oxd server
https://github.com/GluuFederation/oxd/issues/182
=> #182 - Add tracing metrics to oxd server

docs/sources/api/index.md
#67 - Correcting `update-site` description and other text on api page.
https://github.com/GluuFederation/docs-oxd-prod/issues/67
=> #67 - Correcting `update-site` description and other text on api page.

docs/mkdocs.yml, docs/sources/redis-configuration/index.md
#69 - Add document page for 'Redis configuration' in oxd
https://github.com/GluuFederation/docs-oxd-prod/issues/69
=> #69 - Add document page for 'Redis configuration' in oxd

docs/sources/configuration/h2/index.md
#388 - Make h2 database username/password connection details configurable in yml file
https://github.com/GluuFederation/oxd/issues/388
=> #388 - Make h2 database username/password connection details configurable in yml file

docs/sources/configuration/h2/index.md, docs/sources/configuration/oxd-configuration/index.md
#389 - HA : RpService should cache Rp object for configurable amount of time (not indefinitely). 
https://github.com/GluuFederation/oxd/issues/389
=> #389 - HA : RpService should cache Rp object for configurable amount of time (not indefinitely). 

docs/sources/api/index.md, docs/sources/index.md
#390 - Sync client from OP : Update oxd database by reading client 
https://github.com/GluuFederation/oxd/issues/390
=> #390 - Sync client from OP : Update oxd database by reading client 

docs/sources/api/index.md
#363 - Introduce new `/uma-rs-modify` command to be able modify existing resource 
https://github.com/GluuFederation/oxd/issues/363
=> #363 - Introduce new `/uma-rs-modify` command to be able modify existing resource 

docs/mkdocs.yml, docs/sources/configuration/oxd-configuration/index.md, docs/sources/index.md, docs/sources/install/index.md, docs/sources/tutorials/python/index.md
#77 - Correct changes in 4.0, 4.1, 4.2 branch of oxd docs 
https://github.com/GluuFederation/docs-oxd-prod/issues/77
This PR is to correct branch 4.2.
=> #77 - Correct changes in 4.2 branch of oxd docs 

docs/sources/configuration/oxd-configuration/index.md
#384 - Remove ability to set/update Pre-Authorization flag from oxd 
https://github.com/GluuFederation/oxd/issues/384
=> #384 - Remove ability to set/update Pre-Authorization flag from oxd 

docs/sources/api/index.md
#165 - UMA : add creation and expiration resource support to oxd
https://github.com/GluuFederation/oxd/issues/165
=> #165 - UMA : add creation and expiration resource support to oxd

docs/mkdocs.yml, docs/sources/configuration/h2/index.md, docs/sources/configuration/jdbc/index.md, docs/sources/configuration/redis/index.md
#430 - Add support for JDBC connection to be able connect to any RDBMS
https://github.com/GluuFederation/oxd/issues/430
=> #430 - Add support for JDBC connection to be able connect to any RDBMS

docs/sources/configuration/oxd-configuration/index.md
#364 - Add support for proxy configuration 
https://github.com/GluuFederation/oxd/issues/364
=> #364 - Add support for proxy configuration 

docs/sources/configuration/oxd-configuration/index.md
#456 - Adding new fields in oxd-server.yml
https://github.com/GluuFederation/oxd/pull/456
=> #456 - Adding new fields in oxd-server.yml

docs/mkdocs.yml, docs/sources/4.x-intro.md, docs/sources/api/index.md, docs/sources/index.md, docs/sources/release-notes/index.md, docs/sources/tutorials/windowsInstaller/index.md, docs/sources/upgrade/index.md
=> #96 - Upgrade oxd 4.2.0 docs 

docs/sources/4.x-intro.md, docs/sources/api/index.md, docs/sources/tutorials/python/index.md, docs/sources/tutorials/windowsInstaller/index.md
=> #96 Upgrade oxd 4.2.0 docs 

docs/sources/configuration/oxd-configuration/index.md
#503 - Add `bindHost` with default value localhost 
https://github.com/GluuFederation/oxd/issues/503
=> #503 - Add `bindHost` with default value localhost 

docs/sources/api/index.md
#499 - Passing `Request Object by Value` and `Request Object by Reference` in Authorization Request
https://github.com/GluuFederation/oxd/issues/499
=> #499 - Passing `Request Object by Value` and `Request Object by Reference` in Authorization Request
